Add disable aggregator setting
LlamaSwap/interface pull request #136
Opened 2023-03-15 16:06 UTC by vrtnd

2023-03-15 21:52 UTC, 0xngmi requested changes
biggest issue is that when we add new adapters those will be disabled by default to all our users

solution is to use a blacklist instead of a whitelist

2023-03-15 21:52 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +					{isLoading && debouncedAmount && finalSelectedFromToken && finalSelectedToToken && enabledAdapters.length ? (
why add this here?

2023-03-15 21:52 UTC, 0xngmi commented on src/components/Aggregator/Settings.tsx
> +			isChecked ? adapters.concat(name) : adapters.filter((adapterName) => adapterName !== name)
please don't shadow existing variables, adapters is already defined in the outer scope

2023-03-16 12:49 UTC, 0xngmi commented on src/components/Aggregator/Settings.tsx
>  		const isChecked = e.target.checked;
does this hold the state before the change or after the change on click?

2023-03-16 14:44 UTC, vrtnd commented on src/components/Aggregator/Settings.tsx
>  		const isChecked = e.target.checked;
event has new state after click

2023-03-16 16:33 UTC, 0xngmi approved these changes

2023-03-16 17:43 UTC, 0xngmi approved these changes

2023-03-16 17:43 UTC, merged