Fix zero slippage, mobile route layout
LlamaSwap/interface pull request #203
Opened 2023-06-28 09:34 UTC by vrtnd

2023-07-02 02:33 UTC, mintdart submitted a review, later dismissed

2023-07-02 02:34 UTC, 0xngmi requested changes
should fix 0 slippage trades, not forbid them

2023-07-04 04:46 UTC, mintdart approved these changes

2023-07-15 15:51 UTC, 0xngmi approved these changes

2023-07-15 15:51 UTC, merged