feat: fallback pricing with dexscreener
LlamaSwap/interface pull request #257
Opened 2024-02-15 04:43 UTC by fhd1423

Use dexscreener pricing for assets that are brand new (shitcoins) that are not listed on coingecko yet. Gets the average price across liquidity pools above 10k usd TVL.

2024-05-12 02:42 UTC, 0xngmi requested changes

2024-05-12 02:42 UTC, 0xngmi commented on src/queries/useGetPrice.tsx
> +			fromTokenPrice =
need to fetch missing experimental prices in parallel so its faster if both are missing

2024-05-12 02:42 UTC, 0xngmi commented on src/queries/useGetPrice.tsx
> +		const expirementalPrices = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${token}`).then((res) =>
if there are two tokens on different chains that share the same address this will match tokens incorrectly

this sometimes happens with bridged tokens so it could be abused on purpose

2024-05-12 13:31 UTC, 0xngmi commented on src/queries/useGetPrice.tsx
> +				return acc + Number(pair.priceUsd);
average weighted by liquidity would be harder to manipulate than strict average?

although i guess it would get arbed? is there any way the liquidity number could be manipulated with something like fake tokens?

2024-05-13 00:29 UTC, fhd1423 commented on src/queries/useGetPrice.tsx
> +				return acc + Number(pair.priceUsd);
i switched it to weighted by liquidity. pretty sure dexscreener filters out fake weth/usdc and stuff like that already.

2024-06-07 19:35 UTC, merged