add 0x gasless swaps
LlamaSwap/interface pull request #266
Opened 2024-04-11 10:55 UTC by mintdart

2024-04-12 02:34 UTC, 0xngmi requested changes
will this work for tokens like USDT that dont have EIP712 support? doesnt look like it, but matcha supports it

2024-04-13 00:27 UTC, mintdart commented
> will this work for tokens like USDT that don't have EIP712 support? doesn't look like it, but matcha supports it

I tested a swap from USDT to DAI on polygon, their api doesn't return any signature errors

Right now my test swap fails because of `order not fillable` , will try to swap on mainnet
<img width="276" alt="Screenshot" src="https://github.com/LlamaSwap/interface/assets/96025197/a15cf1e5-83eb-41bc-bf4c-0bdb581184f0">

2024-04-18 05:09 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xGasless.tsx
> +		extra.amountOut && extra.amountOut !== '0' ? `buyAmount=${extra.amountOut}` : `sellAmount=${amount}`;
if its possible to trade with output amount then you must set `export const isOutputAvailable = true;`

2024-04-18 06:04 UTC, mintdart commented
> main thing missing is to separate the approval process, so its in two steps (rather than 2 popups that pop automatically) and user can choose whether to approve infinite or approve only amount needed in permits

updated

2024-04-18 06:06 UTC, mintdart commented on src/components/Aggregator/adapters/0xGasless.tsx
> +		amountReturned: data?.buyAmount || 0,
copied it from 0x adapter, removed it

2024-04-18 06:06 UTC, mintdart commented on src/components/Aggregator/adapters/0xGasless.tsx
> +		extra.amountOut && extra.amountOut !== '0' ? `buyAmount=${extra.amountOut}` : `sellAmount=${amount}`;
updated

2024-04-19 05:07 UTC, 0xngmi submitted a review, later dismissed
minor comments, besides that leaving here two reminders for when it goes live:
- need to set it as one of those adapters where we query our backend always
- move api key to env var & replace it

also, is it possible to cancel 0x gasless orders like how you can cancel cowswap ones?

2024-04-19 09:25 UTC, mintdart commented on src/components/Aggregator/adapters/0xGasless.tsx
> +		domain: rawQuote.trade.eip712.domain,
added https://github.com/LlamaSwap/interface/pull/266/commits/2aaf0b9afed530bd78a0610ae0ffe74a9224a9b6

2024-04-19 09:39 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +		(selectedRoute.price.rawQuote as any).approval.isRequired &&
updated in https://github.com/LlamaSwap/interface/pull/266/commits/d772194a8d7d82db00bc41e522d6d214592e6cfc

2024-04-20 03:37 UTC, mintdart commented
> minor comments, besides that leaving here two reminders for when it goes live:
> 
> * need to set it as one of those adapters where we query our backend always
> * move api key to env var & replace it
> 
> also, is it possible to cancel 0x gasless orders like how you can cancel cowswap ones?

updated code to query our backend always and use api key in env var

currently it's not possible to cancel orders by external party

2024-04-20 15:13 UTC, 0xngmi reviewed
hmm no retries on pending txs? or did i miss it?

2024-04-21 13:46 UTC, mintdart commented
> hmm no retries on pending txs? or did i miss it?

added in https://github.com/LlamaSwap/interface/pull/266/commits/993f58be9f545773be21bd41b4feb864987f63ce

2024-05-10 02:45 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +														isConfirmingApproval || selectedRoute?.isGasless || gaslessApprovalMutation.isLoading
won't `selectedRoute?.isGasless` always be true when on a gasless route?

2024-05-10 02:45 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +																	isConfirmingApproval || selectedRoute?.isGasless || gaslessApprovalMutation.isLoading
same here

2024-05-10 04:23 UTC, 0xngmi commented on server/src/submitSwap.ts
> +	const agg = adapters.find((ag) => decodeURIComponent(ag.name) === protocol);
turns out that AWS API Gateway always decodes querystring params, so this is not needed at all

2024-05-10 04:25 UTC, 0xngmi commented on server/src/submitSwap.ts
> +	const agg = adapters.find((ag) => decodeURIComponent(ag.name) === protocol);
removed decoding

2024-05-10 04:25 UTC, 0xngmi commented on server/src/submitSwap.ts
> +		body: JSON.stringify(res)
added headers

2024-05-10 15:49 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +														isConfirmingApproval || selectedRoute?.isGasless || gaslessApprovalMutation.isLoading
correct, removed in https://github.com/LlamaSwap/interface/pull/266/commits/6b27c11a410773f517c9c54c9e4b4e51e16c49b1

2024-05-10 17:05 UTC, 0xngmi submitted a review, later dismissed

2024-05-11 18:28 UTC, merged