WIP: Add yields and lending
LlamaSwap/interface pull request #271
Opened 2024-05-22 20:59 UTC by vrtnd

2024-05-23 08:18 UTC, 0xngmi requested changes

2024-05-23 08:18 UTC, 0xngmi commented on src/components/Aggregator/Yileds.tsx
> +import React, { memo, useLayoutEffect, useState, useRef } from 'react';
ser try to avoid these typos, it's yields not Yileds

2024-06-25 10:57 UTC, 0xngmi requested changes

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +		[initialData.length]
why use initialData.length instead of initialData?

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +		[initialData.length]
why use initialData.length instead of initialData?

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +					console.log({ search, symbolMatch, item });
delet

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +			handleFilterChanges({ ...query, [key]: value });
is it possible that because handleFilterChanges is only called here that if a user comes with filters applied in query this won't get called and thus filters not applied?

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +import { debounce } from 'lodash';
https://llamaswap-git-yields-llamapay.vercel.app/?tab=yields&search=ETH&chains=BSC&chain=ethereum&from=0x0000000000000000000000000000000000000000

crashes

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +		setData(initialData);
the manipulations of data directly are kinda sus, why not just store all state in query and then have something that calculates data based on that state?

2024-06-25 10:57 UTC, 0xngmi commented on src/components/Yields/index.tsx
> +	console.log(tokens);
delet

2024-06-25 11:02 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +			handleFilterChanges({ ...query, [key]: value });
indeed this is happening right now, if you go to https://llamaswap-git-yields-llamapay.vercel.app/?tab=earn&search=ETH&chains=BSC&chain=ethereum&from=0x0000000000000000000000000000000000000000 directly you'll see that filters aren't being correctly applied

2024-07-02 03:18 UTC, 0xngmi approved these changes
some minor issues but looks good enough to merge rn and then let's do another PR later improving on these issues

2024-07-02 03:18 UTC, 0xngmi commented on src/components/Yields/index.tsx
> +		return allTokens.map((token: Record<string, string>) => ({
can we sort tokens by mcap?

2024-07-02 03:18 UTC, 0xngmi commented on src/pages/index.tsx
> +	const yeildProps = useYieldProps();
need to avoid fetching all this info unless we need it, so unless user goes to earn/borrow page

2024-07-02 03:18 UTC, 0xngmi commented on src/props/getLendingProps.ts
> +	const lendingData = await getLendBorrowData(yields);
Promise.all([yields, lendingData]) to fetch both in parallel

should apply this to everywhere where we make multiple async queries since it will speed up stuff a lot (2x in this case)

2024-07-02 03:18 UTC, 0xngmi commented on src/components/Lending/index.tsx
> +		setLendingPools(filterPools(initialData, selectedLendToken, true));
seeing this pattern where you use useEffect to modify a useState, why not use useMemo here instead?

2024-07-03 13:05 UTC, mintdart commented
Also token images are missing in dropdown

2024-07-03 13:09 UTC, mintdart commented
Borrow UI is cropped on mobile, can't horizontally scroll
<img width="343" alt="Screenshot" src="https://github.com/LlamaSwap/interface/assets/96025197/e8cbb94e-1ea7-4f76-bbb7-4e49a10d1577">

2024-07-03 13:12 UTC, mintdart commented
sorting arrow next to 30d APY is hidden
![Uploading Screenshot 1.png…]()

2024-07-03 13:21 UTC, mintdart commented
Cannot search for tokens by symbol
<img width="702" alt="Screenshot 2" src="https://github.com/LlamaSwap/interface/assets/96025197/ce4314e3-f6d8-4065-ad7f-7f5dbf1961c2">

2024-07-03 13:23 UTC, mintdart commented on src/pages/index.tsx
> +	const yeildProps = useYieldProps();
Also if possible lazy load earn / borrow components

2024-07-04 01:04 UTC, mintdart approved these changes

2024-07-04 16:54 UTC, merged