integrate 0x v2
LlamaSwap/interface pull request #278
Opened 2024-06-13 09:23 UTC by mintdart

2024-06-27 00:13 UTC, mintdart commented
Note: Replace api key before merging

2024-06-28 20:10 UTC, 0xngmi requested changes

2024-06-28 20:10 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xV2.ts
> +		tokenApprovalAddress: data.permit2 ? data.permit2.eip712.domain.verifyingContract : null,
can we hardcode this? esp since we allow infinite approvals against it

2024-06-30 07:56 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +		tokenApprovalAddress: data.permit2 ? data.permit2.eip712.domain.verifyingContract : null,
we already have a approval address check here https://github.com/LlamaSwap/interface/pull/278/files#diff-e94408b53437edb793602d5f10b1f515df45f2048f48870c468137dbb4b66387R61

2024-07-03 01:03 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xV2.ts
> +	const gas = chain === 'optimism' ? BigNumber(3.5).times(data.transaction.gas).toFixed(0, 1) : data.transaction.gas;
imo lets remove this

2024-07-03 01:03 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xV2.ts
> +		if (r.status !== 200) {
why not check status first?

2024-07-03 01:07 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xV2.ts
> +}
missing the function that returns calldata?

2024-07-03 01:21 UTC, 0xngmi commented on src/components/Aggregator/list.ts
> +	matchaV2.name
no infinite approval for now

2024-07-03 05:34 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +				'0x-api-key': 'e3fae20a-652c-4341-8013-7de52e31029b'
yes , added it for testing purposes

I added a comment in this PR to remove it before merging

2024-07-03 05:40 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +}
added

2024-07-03 05:40 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +		if (r.status !== 200) {
updated

2024-09-27 15:36 UTC, 0xngmi approved these changes

2024-09-27 15:36 UTC, 0xngmi commented on src/components/Aggregator/adapters/0xV2.ts
> +				permitApiQuote.permit2.eip712.domain.verifyingContract.toLowerCase() !== permit2Address.toLowerCase()
this check seems useless? since verifyingContract is never used

2024-09-28 03:24 UTC, phil-ociraptor commented on src/components/Aggregator/adapters/0xV2.ts
> +		data: signature
Hey there! Chiming in on this line - since the code was first written, we have changed how the Permit2 signature needs to be encoded in the calldata

Instead of find and replace of the magic string, we append the signature size and signature at the end. Instructions and code sample here: https://0x.org/docs/0x-swap-api/guides/swap-tokens-with-0x-swap-api#5-append-signature-length-and-signature-data-to-transactiondata

2024-09-28 04:59 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +		...(chain === 'optimism' && { gasLimit: rawQuote.gasLimit })
removed

2024-09-28 05:01 UTC, mintdart commented on src/components/Aggregator/adapters/0xV2.ts
> +				permitApiQuote.permit2.eip712.domain.verifyingContract.toLowerCase() !== permit2Address.toLowerCase()
if user has enough allowance for permit2Address then permit2 will be null

no need for approval signature, but user can sign -> swap via permit2 

instead of approving spender from allowanceHolderApiQuote -> swap

example: they approved on matcha.xyz or uniswap.org and trying to swap on llamaswap , we don't need to ask them to approve again

2024-09-30 20:39 UTC, phil-ociraptor approved these changes
PR looks good from my perspective! 

I tried pulling the repo and testing but wasn't able to get the lambdas working (so in my tests, the lambdas were just pointed at prod). In my testing, it appeared the tx went down the AllowanceHolder flow just fine, which is sufficient to start.

That said, I was unable to test the permit2 flow. Happy to help out with testing if you guys need it

For now, things look good from our side - just requesting a rename from Argon => 'Matcha/0x v2'

2025-05-01 02:23 UTC, 0xngmi approved these changes

2025-05-09 15:01 UTC, 0xngmi approved these changes

2025-05-09 16:50 UTC, merged