Yields fixes
LlamaSwap/interface pull request #283
Opened 2024-07-08 08:56 UTC by vrtnd

2024-07-10 19:48 UTC, 0xngmi requested changes

2024-07-10 19:48 UTC, 0xngmi commented on src/components/Lending/index.tsx
>  					.flat()
this flat() may be unnecessary?

2024-07-10 19:48 UTC, 0xngmi commented on src/components/Lending/index.tsx
> +						selectedBorrowToken === 'STABLES' || borrowPool?.category === 'CDP'
technically there can be CDPs against other currencies, eg reflexer is a cdp against a coin thats worth ~3.14$

2024-07-10 19:48 UTC, 0xngmi commented on src/components/Yields/Filters.tsx
> +						apy: item.apy - (item.apyReward || 0)
why negative?

2024-07-10 19:48 UTC, 0xngmi commented on src/components/Yields/index.tsx
> +		<YieldsCell>{data[index].apy.toFixed(2)}%</YieldsCell>
why change this?

2024-07-10 19:48 UTC, merged

2024-07-11 09:35 UTC, vrtnd commented on src/components/Yields/Filters.tsx
> +						apy: item.apy - (item.apyReward || 0)
apy is sum of apyReward + apyBase

2024-07-11 09:37 UTC, vrtnd commented on src/components/Yields/index.tsx
> +		<YieldsCell>{data[index].apy.toFixed(2)}%</YieldsCell>
see ^