update dependencies
LlamaSwap/interface pull request #290
Opened 2024-09-11 00:57 UTC by mintdart

2024-11-28 22:28 UTC, 0xngmi requested changes
some stuff, not fully reviewed yet

2024-11-28 22:28 UTC, 0xngmi commented on src/hooks/useCountdown.ts
> +		return;
what change does this make?

2024-11-28 22:28 UTC, 0xngmi commented on tsconfig.json
> -	"exclude": ["node_modules", "cypress", "server"],
why did we have cypress here?

2024-11-29 04:17 UTC, mintdart commented on tsconfig.json
> -	"exclude": ["node_modules", "cypress", "server"],
It's from uniswap's frontend, which we forked to build defillama-app, and then forked defillama-app to build llamaswap

2024-11-29 04:17 UTC, mintdart commented on src/components/Aggregator/adapters/llamazip/encode.ts
> +export function encode2(
https://discord.com/channels/@me/926913780116500581/1286620483458039890

2024-11-29 04:23 UTC, mintdart commented on src/components/Aggregator/adapters/0xGasless.ts
> +				recoveryParam: 1 - (approvalSignature.v % 2),
it's from 0x docs, they link to https://github.com/0xProject/0x-examples/blob/main/gasless-v2-headless-example/utils/signature.ts#L37 on how to split signature

2024-11-29 04:28 UTC, mintdart commented on src/hooks/useCountdown.ts
> +		return;
fixes a warning to return something from useEffect
<img width="609" alt="Screenshot" src="https://github.com/user-attachments/assets/62c907b6-f68c-43b8-8feb-3356792f180c">

2024-11-29 05:02 UTC, mintdart commented on src/components/Aggregator/hooks/useEstimateGas.ts
> +		(chain === 'polygon' && isOutput)
i don't recall why added chain === 'polygon' && isOutput), removed

2024-11-29 05:32 UTC, mintdart commented on src/components/WalletProvider/chains.ts
> +		default: { http: ['https://evm.cronos.org'] }
I've already updated to use those rpcs , these rpc url's to satisfy wagmi's `Chain` type
<img width="506" alt="Screenshot 2" src="https://github.com/user-attachments/assets/603d19aa-edc7-4fd9-bd35-a1c7b9f855b0">

https://github.com/LlamaSwap/interface/blob/update-deps-1/src/components/WalletProvider/index.tsx#L12

https://github.com/LlamaSwap/interface/blob/update-deps-1/src/components/Aggregator/rpcs.ts#L250

2024-11-29 07:37 UTC, mintdart commented on src/components/Aggregator/index.tsx
> -	const priceImpactRoute = selectedRoute ? fillRoute(selectedRoute) : null;
we already fillRoute in normalizedRoutes

2024-11-29 07:40 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +
if useEstimateGas is still loading, `gasData?.[route.name]?.gas` will be undefined anyways

2024-11-29 07:42 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> -		isLoaded: loadingRoutes.length === 0,
we don't use isLoaded anywhere

2024-12-05 18:38 UTC, 0xngmi requested changes
Also:
- fix merge conflict

2024-12-05 18:38 UTC, 0xngmi commented on src/components/Aggregator/hooks/useTokenApprove.ts
> +	const { mutateAsync: approveWriteContract, isPending: isLoading } = useApproveTokenSpend();
useApproveTokenSpend and the calculation for gas limit use different abis for the approve call, former uses a custom abi you set while latter uses the one provided by viem

this could cause issues with tokens that have weird approves, like usdt, imo change it to use the same abi in both cases

2024-12-05 18:38 UTC, 0xngmi commented on src/components/WalletProvider/chains.ts
>  const cronos = {
id apply the changes in the map() function but well this works too

2024-12-05 18:38 UTC, 0xngmi commented on src/queries/useGetSavedTokens.tsx
> +	if (!chainId) return {};
shouldnt this return [] in case of failure?

2024-12-05 18:39 UTC, 0xngmi commented on src/components/Aggregator/adapters/llamazip/encode.ts
> +	word = BigInt(String(BigNumber.from(String(word << 2n)).add(slippageId)));
applied this

2024-12-05 19:39 UTC, 0xngmi commented on src/components/WalletProvider/chains.ts
>  const cronos = {
for now lets leave as is

2024-12-05 21:52 UTC, 0xngmi requested changes

2024-12-05 21:52 UTC, 0xngmi commented on src/queries/useTokenBalances.tsx
> +	if (!address || !chain) return {};
damn why did we have [] here instead of {}?

2024-12-05 21:52 UTC, 0xngmi commented on src/queries/useGetRoutes.tsx
> +			return {
since the same object is used twice, can you declare it as a variable somewhere and return it? to avoid repeating stuff that makes it error prone

2024-12-05 21:52 UTC, 0xngmi commented on src/queries/useGetRoutes.tsx
> -			?.filter((r: [string, UseQueryResult<IRoute>]) => r[1].status === 'loading') ?? [];
btw is it possible that the order here is wrong? cause there have been some cases where i see the wrong adapter being displayed as loading and now looking at this code i see its making an assumption on ordering that might be wrong

instead would be better to fetch adapter/aggregator name from the object directly

2024-12-05 21:52 UTC, 0xngmi commented on src/queries/useGetRoutes.tsx
> +			isLoading: res.length > 0 && data.length === 0
why is it that previously we returned isLoading: true when `data.length < 1`, and now we return it as long as`res.length > 0 && data.length === 0`, yet when i check the frontend it seems to work fine?

2024-12-05 21:52 UTC, 0xngmi commented on src/queries/useGetRoutes.tsx
> +					.sort((a, b) => a.dataUpdatedAt - b.dataUpdatedAt)?.[0]?.dataUpdatedAt ?? Date.now(),
is there any chance useMemo could mess up with Date.now() by introducing a caching layer? i don't think so but unsure

2024-12-06 08:15 UTC, mintdart commented on src/queries/useGetSavedTokens.tsx
> +	if (!chainId) return {};
yes, updated

2024-12-06 08:17 UTC, mintdart commented on src/queries/useTokenBalances.tsx
> +	if (!address || !chain) return {};
that bug was introduced in this commit https://github.com/LlamaSwap/interface/commit/e76cafbf376c13cdb2689f9385cacf4eb046a974 , rip...

2024-12-06 08:35 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> -			?.filter((r: [string, UseQueryResult<IRoute>]) => r[1].status === 'loading') ?? [];
you are correct, updated

2024-12-06 08:40 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> +			isLoading: res.length > 0 && data.length === 0
sometimes chainAdpaters.length might be 0 here
<img width="897" alt="Screenshot 1" src="https://github.com/user-attachments/assets/4f429892-3712-43a3-aee7-c6718a24cff8">

then we will still show `Loading...` even tho there are no routes available to query

2024-12-06 08:48 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> +					.sort((a, b) => a.dataUpdatedAt - b.dataUpdatedAt)?.[0]?.dataUpdatedAt ?? Date.now(),
nope, lastFetched === Date.now() only when all routes are is still loading , we don't show the refetch button on top right at that time so shouldn't be an issue
<img width="1038" alt="Screenshot 3" src="https://github.com/user-attachments/assets/a2e53373-5257-4b10-bf11-83124c294347">
<img width="972" alt="Screenshot 2" src="https://github.com/user-attachments/assets/20cb392d-b530-47e9-81bf-0006f2b51c9a">

2024-12-06 08:59 UTC, mintdart commented on src/queries/useBalance.tsx
> +		return { value: result[0], formatted: formatUnits(result[0], result[1]), decimals: result[1] };
it's not possible, readContracts is similar to Promise.all()

2024-12-06 09:03 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> +			return {
updated

2024-12-06 09:09 UTC, mintdart commented on src/components/Aggregator/hooks/useEstimateGas.ts
> +			const swapTx = response.result[2];
update to `const swapTx = response.result[response.result.length - 1]` in https://github.com/LlamaSwap/interface/pull/290/commits/a7e228604a50667f4e3c6a6218387f3ce758c8bd

2024-12-06 09:21 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +								disabled={!selectedChain}
it might be null if you navigate to this url https://llamaswap-git-update-deps-1-llamaswap.vercel.app/?chain=basee&from=0x0000000000000000000000000000000000000000&tab=swap&to=

removed `disabled` and updated to show this toast in https://github.com/LlamaSwap/interface/pull/290/commits/5669d5ffac0e7359be21b6fd9d17d47dc42d04ad
<img width="1008" alt="Screenshot" src="https://github.com/user-attachments/assets/1a9e363d-7956-4b00-8fa1-0b8dc5ba6032">

2024-12-06 09:43 UTC, 0xngmi commented on src/components/Aggregator/hooks/useTokenApprove.ts
> +	const { mutateAsync: approveWriteContract, isPending: isLoading } = useApproveTokenSpend();
did you test if it works well with usdt btw?

2024-12-06 10:31 UTC, 0xngmi requested changes

2024-12-06 10:31 UTC, 0xngmi commented on src/components/Aggregator/hooks/useTokenApprove.ts
> +					abi: [
just create a const with that and then use it twice? instead of having the same object duplicated twice?

2024-12-06 10:31 UTC, 0xngmi commented on src/queries/useGetRoutes.tsx
> +				?.map((r, i) => [chainAdapters[i].name, r] as [string, UseQueryResult<IAdapterRoute>])
there's still an assumption that useQueries() will maintain ordering, did you test that assumption?

2024-12-06 11:24 UTC, mintdart commented on src/components/Aggregator/hooks/useTokenApprove.ts
> +	const { mutateAsync: approveWriteContract, isPending: isLoading } = useApproveTokenSpend();
yes

2024-12-06 11:51 UTC, mintdart commented on src/components/Aggregator/hooks/useTokenApprove.ts
> +					abi: [
updated in https://github.com/LlamaSwap/interface/pull/290/commits/9341d7b26d3207d2d0c4b84f21845e804a33c05e

2024-12-06 11:57 UTC, mintdart commented on src/queries/useGetRoutes.tsx
> +				?.map((r, i) => [chainAdapters[i].name, r] as [string, UseQueryResult<IAdapterRoute>])
im not sure how to test it, but useQueries is similar to Promise.all() so i assume it should maintain the order ?
`data` will be undefined when query is still fetching and we do not have access to queryKey to get the adapter name
<img width="402" alt="Screenshot" src="https://github.com/user-attachments/assets/cc2cc8a2-43b2-41fa-a7bc-c40462fe1e37">

2024-12-06 15:02 UTC, vrtnd commented on src/hooks/useQueryParams.tsx
> +			if (isConnected && chainOnWallet && chain) {
because now wallets arent forcing to switch chains like metamask did?

2024-12-06 15:40 UTC, 0xngmi commented on src/hooks/useQueryParams.tsx
> +			if (isConnected && chainOnWallet && chain) {
i think its just because its used afterwards in the code?

2024-12-06 15:43 UTC, 0xngmi submitted a review, later dismissed

2024-12-06 16:07 UTC, vrtnd approved these changes

2024-12-06 16:44 UTC, mintdart commented on src/hooks/useQueryParams.tsx
> +			if (isConnected && chainOnWallet && chain) {
in wagmi's v2, if chain isn't supported, `chain` will be undefined instead of `chain.unsupported = true`

2024-12-06 17:00 UTC, merged