UX: Number formatting, new layout for routes, smaller IP switch
LlamaSwap/interface pull request #44
Opened 2023-01-16 23:56 UTC by ai-slave

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6696080/212781934-f17634a5-b7ab-40ee-a410-e12c10c191e6.png">

2023-01-18 15:06 UTC, 0xngmi commented
![image](https://user-images.githubusercontent.com/80541789/213207038-4c85130d-ad25-4a22-bc0d-3cc462d50284.png)
smol bug when gas cost is unknown

2023-01-18 15:09 UTC, 0xngmi commented
unsure about adding price below each quote since it seems a bit redundant, whats the rationale behind that?

2023-01-18 15:17 UTC, ai-slave commented
@0xngmi to compare what was the initial quote from the aggregator. But maybe a good place to put "~ $9,900 After fees"?

2023-01-18 15:54 UTC, ai-slave commented
@0xngmi updated to this version 
![Uploading image.png…]()

Price is being shown in #50, I'll maybe iterate a little later to incorporate highlighting high impact orders on the list of routes, so you can understand it's not good before you click on it.

2023-01-18 16:48 UTC, ai-slave commented
removed .toFixed(3) on final amount that you're getting
![image](https://user-images.githubusercontent.com/6696080/213243166-a05b14a6-81be-4238-ad14-641a05f91817.png)

2023-01-18 20:11 UTC, ai-slave commented
Anything else weird left on this one?

2023-01-18 21:22 UTC, 0xngmi commented
looks good, will review in a bit again and ask for more reviews

2023-01-19 21:40 UTC, 0xngmi commented
sorry but recently merged a PR that made a lot of changes, could you fix the merge conflicts?

2023-01-19 23:00 UTC, ai-slave commented
@0xngmi done

2023-01-19 23:58 UTC, mintdart requested changes
can you update this row color, it is a bit harder to read
![Screenshot 1](https://user-images.githubusercontent.com/96025197/213588400-5ebf884c-a320-4e0f-8a21-e1d014644100.png)

2023-01-20 00:06 UTC, mintdart submitted a review, later dismissed

2023-01-20 00:15 UTC, mintdart commented
> can you update this row color, it is a bit harder to read ![Screenshot 1](https://user-images.githubusercontent.com/96025197/213588400-5ebf884c-a320-4e0f-8a21-e1d014644100.png)

Please ignore this, I've changed it in my last commit

2023-01-20 00:25 UTC, mintdart commented
on mobile
![Screenshot](https://user-images.githubusercontent.com/96025197/213591361-ef9a1322-efb4-408f-bfba-900e0f16ce27.png)

2023-01-20 13:58 UTC, 0xngmi commented
![image](https://user-images.githubusercontent.com/80541789/213714397-1b99b49f-9307-4713-a6be-df4e9e8dca93.png)
z-index issue

2023-01-20 14:43 UTC, ai-slave commented
@0xngmi can't reproduce, but topped zindex, please check

2023-01-20 15:02 UTC, 0xngmi commented
still seeing same issue, on prod at https://llamaswap-git-fork-ai-slave-master-llamapay.vercel.app/ (tested with brave and firefox)

2023-01-20 22:05 UTC, ai-slave commented
@0xngmi should be fixed

2023-01-20 22:11 UTC, mintdart commented
I still see z-index issue on https://llamaswap-git-fork-ai-slave-master-llamapay.vercel.app/?from=0x0000000000000000000000000000000000000000&to=0x4d224452801aced8b2f0aebe155379bb5d594381
![Screenshot](https://user-images.githubusercontent.com/96025197/213814303-0b35986a-71f0-48d9-9ae0-57f50f72291d.png)

2023-01-20 22:19 UTC, ai-slave commented
Fixed, thank you guys for testing it. I'll try to do better :|

2023-01-20 22:29 UTC, mintdart commented
> Fixed, thank you guys for testing it. I'll try to do better :|

If z-index is -1, you can't select any route

2023-01-20 22:44 UTC, ai-slave commented
fixed, layers should be fine now

2023-01-20 22:56 UTC, mintdart commented
on mobile :|
![Screenshot](https://user-images.githubusercontent.com/96025197/213819824-d850ef69-2892-4d1f-8aaf-316d9e303a8b.png)

2023-01-20 23:14 UTC, ai-slave commented
fixed 👼 thank you

2023-01-21 02:12 UTC, 0xngmi commented
your fix might not have been pushed because of mintdart's commit, after which you need to rebase

2023-01-21 11:15 UTC, ai-slave commented
yeah sorry, just forgot to push :/

2023-01-21 14:29 UTC, 0xngmi approved these changes
minimal stuff, good to merge

2023-01-21 14:29 UTC, 0xngmi commented on src/utils/index.tsx
> +		return symbol ? `${currencySymbol}0` : 0;
wouldnt it be better to properly fix these cases to report 0 instead of something weird?

2023-01-21 14:32 UTC, ai-slave commented on src/utils/index.tsx
> +		return symbol ? `${currencySymbol}0` : 0;
I got this function from Llama main dashboard, but the use case changed a little so yeah, I'll need to rewrite it and take off junk

2023-01-21 14:43 UTC, 0xngmi commented
new ui bussin frfr

2023-01-21 14:44 UTC, 0xngmi commented on src/utils/index.tsx
> +		return symbol ? `${currencySymbol}0` : 0;
imo already good to merge, gonna wait for minty's greenlight and merge

2023-01-21 18:42 UTC, mintdart approved these changes

2023-01-21 18:42 UTC, merged