add price impact
LlamaSwap/interface pull request #50
Opened 2023-01-17 23:07 UTC by mintdart

2023-01-18 00:33 UTC, mintdart commented
![Screenshot 7](https://user-images.githubusercontent.com/96025197/213048927-2d9955b4-62a3-4095-acc9-96799f2fc215.png)
![Screenshot 8](https://user-images.githubusercontent.com/96025197/213049601-5dd7bc30-e4e3-470f-a12b-3707ba2ca2d6.png)

2023-01-18 16:48 UTC, vrtnd approved these changes

2023-01-18 17:54 UTC, 0xngmi requested changes

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Slippage/index.tsx
> +	const { slippage } = useQueryParams();
i'd avoid setting slippage from query params, someone could use that to trick someone else into a high slippage trade and the make mev out of it

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Slippage/index.tsx
> +						setCustomSlippage('');
is customSlippage just being used as a variable to trigger  useEffect()?

2023-01-18 17:54 UTC, 0xngmi commented on src/components/PriceImpact/index.tsx
> +		Number.isNaN(Number(toTokenPrice)) ||
thinking that we could display some warning if we cant get token price for one of the tokens, this could help users be more careful in those cases, as weird tokens are the cases where its the most common price impact to be large because they are traded in obscure dexs

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Slippage/index.tsx
> +						setCustomSlippage('');
ah nvm i think i get it now

2023-01-18 17:54 UTC, 0xngmi commented on src/components/PriceImpact/index.tsx
> +			? Number(priceImpactRoute.amount).toFixed(4)
can do this in another pr after this but imo we should standarize some code that handles number displays and works well with either very small numbers (eg 0.000054 WBTC) and large ones (adds commas)

2023-01-18 17:54 UTC, 0xngmi commented on src/components/PriceImpact/index.tsx
> +					).toFixed(4)} ${toToken.symbol} ($${(+fromTokenPrice).toFixed(2)})`}</Box>
from UI I assumed that 
1 ETH = 1500 DAI (1.5k$)

meant that 1500 DAI was 1.5k not that 1 ETH was 1.5k, id display that using toTokenprice*amount

2023-01-18 17:54 UTC, 0xngmi commented on src/components/PriceImpact/index.tsx
> +						{isPriceImpactNotKnown || priceImpact >= 7 ? <WarningTwoIcon style={{ marginLeft: 'auto' }} /> : null}
lets put the 7 somewhere as a constant so future changes can easily change it (instead of hunting for all 7s in codebase or making mistakes)

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +							{route ? (
i think @vrtnd changed this to route?.price because of the crashes, but i dont fully get why

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> -								{balance.isSuccess && balance.data && !Number.isNaN(Number(balance.data.formatted)) ? (
balance display is removed? why?

2023-01-18 17:54 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +											query: { ...router.query, to: finalSelectedFromToken.address, from: finalSelectedToToken.address }
whats the difference between fromToken and finalSelectedFromToken.address?

2023-01-18 18:00 UTC, mintdart commented on src/components/PriceImpact/index.tsx
> +			? Number(priceImpactRoute.amount).toFixed(4)
okay

2023-01-18 18:08 UTC, mintdart commented on src/components/Aggregator/index.tsx
> -								{balance.isSuccess && balance.data && !Number.isNaN(Number(balance.data.formatted)) ? (
thinking of adding balance below tokens select dropdown in a PR, because it looking cramped imo
![Screenshot 5](https://user-images.githubusercontent.com/96025197/213260407-feeccc41-178f-4fe2-8ee5-b7282a199cac.png)

2023-01-18 18:17 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> -								{balance.isSuccess && balance.data && !Number.isNaN(Number(balance.data.formatted)) ? (
agree but imo was very useful below "max", at least id leave for now and change it in a new pr

2023-01-18 18:22 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +											query: { ...router.query, to: finalSelectedFromToken.address, from: finalSelectedToToken.address }
They are same here, I changed it to keep it consistent as we are using finalSelectedFromToken and finalSelectedToToken to get addresses of selected tokens.

`fromToken` - `from` value in URL query param, there might be multiple `from` in URL and that value might be an array also

`selectedFromToken` - if `fromToken` is valid (typeof string), then get that token name, address from our token list , but when user adds a custom token address that isn't in the list, this value will null/undefined

so we use `finalSelectedFromToken` to store `selectedFromToken`, if its `null` fetch token data using `useToken` and assign that result to `finalSelectedFromToken`

2023-01-18 18:40 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +											query: { ...router.query, to: finalSelectedFromToken.address, from: finalSelectedToToken.address }
oke, perfect then

2023-01-18 19:29 UTC, mintdart commented on src/components/Aggregator/index.tsx
> -								{balance.isSuccess && balance.data && !Number.isNaN(Number(balance.data.formatted)) ? (
okay

2023-01-19 14:52 UTC, charlie-eth commented
Few suggestions about proceeding with a high impact price:
- Color scheme needs to be different (people who use the aggregator daily go in self drive mode and won't read anything that doesn't jump out so a bright red warning is the only way to achieve this)
- The double confirmation is good but the button needs to say something different like "Swap with high slippage" instead of just "Swap" (otherwise people don't read and just click Swap twice instead of once) and a colour scheme that's different enough that people won't just ignore it


![image](https://user-images.githubusercontent.com/2455739/213472933-2c79fa92-7e3d-46ef-8651-8ada9b55ec4c.png)

2023-01-19 17:44 UTC, vrtnd submitted a review, later dismissed

2023-01-19 17:44 UTC, vrtnd commented on src/components/Slippage/index.tsx
> +				<Button
smol nit 

``` 
{['0.1', '0.5', '1'].map((slippage) => (
				<Button
					fontSize="0.875rem"
					fontWeight="500"
					p="8px"
					bg="#38393e"
					height="2rem"
					onClick={() => {
						setSlippage(slippage);
					}}
				>
					{slippage}%
				</Button>
			))}
```

2023-01-19 17:47 UTC, vrtnd commented on src/components/Aggregator/index.tsx
> +	}, [finalSelectedToToken]);
need to return other dependencies

2023-01-19 17:48 UTC, vrtnd commented on src/components/Aggregator/index.tsx
> +	}, [finalSelectedToToken]);
or something else sets to token to undefined after selecting it

2023-01-19 18:58 UTC, mintdart commented on src/components/PriceImpact/index.tsx
> +	const isPriceImpactNotKnown = !selectedRoutesPriceImpact && selectedRoutesPriceImpact !== 0;
yes, fixed it

2023-01-19 19:19 UTC, vrtnd commented on src/queries/useGetRoutes.tsx
> -					onSuccess: (data) => {
i think we moved from selecting route to selecting aggregator by name

2023-01-19 19:21 UTC, vrtnd submitted a review, later dismissed

2023-01-19 19:58 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +		priceImpactRoute.amountUsd &&
what if amount that you get is 0?

2023-01-19 19:59 UTC, 0xngmi commented on src/components/Aggregator/index.tsx
> +		priceImpactRoute.amountUsd &&
amountUsd would also be 0 and it would get skipped right?

2023-01-19 20:07 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +		priceImpactRoute.amountUsd &&
amountUsd is a string, so it will be '0' and not get skipped

2023-01-19 20:07 UTC, mintdart commented on src/components/Aggregator/index.tsx
> +		priceImpactRoute.amountUsd &&
![Screenshot 4](https://user-images.githubusercontent.com/96025197/213547786-8230e274-cbbc-4ad4-8e39-10075f5ef50f.png)
we convert to toFixed(2), so it will return a string

2023-01-19 20:27 UTC, 0xngmi submitted a review, later dismissed

2023-01-19 20:42 UTC, vrtnd submitted a review, later dismissed

2023-01-19 21:26 UTC, 0xngmi approved these changes

2023-01-19 21:35 UTC, merged