fix yieldyak
LlamaSwap/interface pull request #60
Opened 2023-01-20 14:56 UTC by vrtnd

2023-01-20 15:20 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +	const gasPrice = await providers[chain].getGasPrice();
why not use extra.gasPriceData.gasPrice if we have it and if not fetch it, this way it will be faster

2023-01-20 15:21 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		estimatedGas: gasEstimate.toString(), // Gas estimates only include gas-cost of swapping and querying on adapter and not intermediate logic, nor tx-gas-cost.
while at it can you fix this gas estimate too?

2023-01-20 16:34 UTC, vrtnd commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		estimatedGas: gasEstimate.toString(), // Gas estimates only include gas-cost of swapping and querying on adapter and not intermediate logic, nor tx-gas-cost.
done

2023-01-20 17:22 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		gas = await estimateGas({ chain, provider, rawQuote: data, from, to, userAddress: extra.userAddress });
this will almost always fail:
- user not connected
- user doesnt have enough balance
- user hasnt approved

instead what id do is do some txs with yield yak and compare gas cost vs what they report, then just add that, at the bare minimum it should be +21k as thats the base tx cost

2023-01-20 17:24 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		gas = await estimateGas({ chain, provider, rawQuote: data, from, to, userAddress: extra.userAddress });
this will almost always fail:
- user not connected
- user doesnt have enough balance
- user hasnt approved
- 
instead what id do is do some txs with yield yak and compare gas cost vs what they report, then just add that, at the bare minimum it should be +21k as thats the base tx cost

2023-01-20 20:00 UTC, 0xngmi requested changes

2023-01-20 20:00 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		gas = await estimateGas({ chain, provider, rawQuote: data, from, to, userAddress: extra.userAddress });
there are some cases where we know this will fail 100%, such as the ones shared in previous comment, where it will just slow down the adapter, in those cases (or at least the easy ones where address = 0x0) id skip this check to keep adapter fast

imo keeping the critical path of adapters fast is very important because otherwise ppl might pick routes that arent best or run into UX problems

2023-01-20 20:24 UTC, mintdart submitted a review, later dismissed

2023-01-21 00:10 UTC, 0xngmi commented
also need to use sendTx or something similar to add extra legroom to gasLimit

2023-01-22 11:39 UTC, vrtnd commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +		amountReturned: data[0][data[0].length - 1].toString(),
no, it wasnt, if return type is tuple ethers adds field names to array prototype along with plain output, but prototype getting removed when we use private mode, so we need to always use tuple

2023-01-22 19:41 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +export async function estimateGas({ chain, rawQuote, from, to, provider, userAddress }) {
hmm is this function not used?

2023-01-22 19:42 UTC, 0xngmi approved these changes
looks good

2023-01-22 19:55 UTC, 0xngmi commented on src/components/Aggregator/adapters/yieldyak/index.ts
> +export async function estimateGas({ chain, rawQuote, from, to, provider, userAddress }) {
removed this bit of code, hope that wasnt wrong

2023-01-22 19:55 UTC, 0xngmi approved these changes

2023-01-22 20:46 UTC, mintdart approved these changes

2023-01-22 23:00 UTC, merged